### ISSUE TITLE
Uncaught Error: Invalid GeoJSON object.

### ISSUE THREAD

**Issue by ThierryPolard** [ThierryPolard/projetSirene#1]
Salut romain, @iOiurson 

Sur la base des cartes et des codes déjà réalisés, j'essaie de faire une carte qui présenterait différents emplacement de sondes sur un cours d'eau, et d'y associer des données pour différents paramètres à différents temps (comme pour les données conso finalement).
A terme, l'objectif serait de pouvoir les selectionner en cliquant dessus, et faire apparaitre sur un volet, des graphs par paramètres, des synthèses à différentes échelle de temps etc.

Sauf que pour l'instant, je n'arrive déjà pas à afficher mes points sur la carte. J'ai 
- repris l'architecture du projet VizLyre
- modifié le dossier data avec des 'dummy data'
- adapté le ficher getAllData.js pour générer un fichier allData.json qui ressemble à ça 

![image](https://cloud.githubusercontent.com/assets/16666814/12843382/3caa2a56-cbf9-11e5-873b-a33791ddddd7.png)

Puis j'essaie d'intégrer cette série de points via mon index.js
`var myLayer = L.geoJson().addTo(map);
myLayer.addData('.js/allData');`

Ca ne marche pas, et la console du navigateur donne le msg suivant 
![image](https://cloud.githubusercontent.com/assets/16666814/12843419/8be226e6-cbf9-11e5-8b03-c4e7cc64fe0b.png)

Je comprends que les données allData sont au format json et non GeoJSON. J'ai essayé de retrouver comment on les avait converties dans le projet précédent, mais je ne retrouve pas. Sur internet, j'ai trouvé un peu de tout : 
- les données Geojson sont de fait des données json, mais dans une mise en forme spécifique, d'où pas besoin de convertisseurs
- des bout de code en python pour convertir (http://gis.stackexchange.com/questions/115733/converting-json-to-geojson-or-csv)
- et d'autres infos que je n'arrive pas à interpréter.

Donc, concrètement, ma question est de savoir ce que je peux faire, à partir de ces éléments, pour avoir des données au format GeoJson que je pourrait afficher sur la map.

[ une autre question aussi.. un peu bête mais...
Quelle est la bonne procédure pour générer  le .json (ou geojson maintenant) à partir du script dans le fichier js ? Ce n'est finalement pas clair pour moi.  J'ai essayé de caler le script dans un HTML, de run dans ConEmu, etc. et au final, je ne sais pas ce qui a marché pour me créer ce fichier............

**Comment by ThierryPolard** [comment]
Dsl, posté un peu vite !
J'espère que c'est assez clair..

Merci d'avance !

**Comment by bleucitron** [comment]
Salut Thierry, ravi de voir que tu as des questions à me poser ^^.

Alors, en effet, le problème est que tu essaies de faire lire à Leaflet des données JSON en lui disant qu'elles sont en format GeoJSON.

Il y a plusieurs manières de résoudre ça, mais d'abord juste pour bien comprendre.

## GeoJSON

Un GeoJSON est effectivement un simple JSON, mais avec un formalisme particulier, adapté pour la représentation de points, lignes, zones géographiques.

Grosso modo, c'est un JSON avec une arborescence de champs qui diffère selon le type de GeoJSON que tu veux:
- Geometry Objects: Point, MultiPoint, LineString, Polygon:

```
{
    type: "Point",
    coordinates: ...
}
```
- GeometryCollection:

```
{
    type: "GeometryCollection",
    geometries: [...] // une liste de Geometry Object
}
```
- Feature: quand tu veux ajouter des paramètres à une géométrie

```
{
    type: "Feature",
    geometry: ... // un Geometry Object
    parameters: ... // des valeurs associées à ta géométrie
}
```
- FeatureCollection: quand tu veux ajouter des paramètres à une géométrie

```
{
    type: "FeatureCollection",
    features: [...] // une liste de Features
}
```

Si tu as des doutes, tu as la spéc complète http://geojson.org/geojson-spec.html#geometry-collection.

## Créer un GeoJSON

Pour créer un GeoJSON, soit tu le fais à la main => bon courage :scream: , soit tu utilises un utilitaire, comme le paquet npm [geojson](https://www.npmjs.com/package/geojson). C'est ce que j'avais fait pour vous montrer.

Par exemple, pour créer un GeoJSON de type Point, tu peux faire:

```
data = [{ name: 'location', lat: 34, lng: 85 }];
GeoJSON.parse(data, {Point: ['lng', 'lat']});
```

ou 

```
data = [{ name: 'location', coords: [85, 34] }];
GeoJSON.parse(data, {Point: 'coords'});
```

N'oublie pas de faire `var GeoJSON = require('geojson');`, sinon ton code ne saura pas ce que c'est `GeoJSON`.
Et fait attention à l'ordre de tes coordonnées, il me semble que c'est `[longitude, latitude]`, mais j'ai un doute.

## Ajouter des layers dans Leaflet

Dans Leafet, on ajoute des layers. Un point est une layer, une ligne est une layer, un polygon est une layer. Tu peux aussi créer des [groupes de layers](http://leafletjs.com/examples/layers-control.html), pour t'éviter d'ajouter des layers de même type une par une.

[Doc de Leaflet](http://leafletjs.com/reference.html#layergroup)

Par exemple:

```
'use strict';

var L = require('leaflet');
var token = 'pk.eyJ1IjoiYW50aGlsbCIsImEiOiJUR0FoRGdJIn0.ZygA4KxIt8hJ1LAvPPMHwQ';

// Create Leaflet Map
var map = L.map('mapID', ...options...); // je crée une layer de type map, et j'insère dans ma div avec l'id mapID.

var position = [44.84, -0.5742];

// Create circle marker
var circleMarker = L.circleMarker(position, ...options...); // je crée une layer de type cercle

// Add markers to map
circleMarker.addTo(map); // j'ajoute ma layer cercle à ma map. addTo() ne marche qu'avec une layer de type L.map en argument
```

Tu remarqueras que là on n'utilise pas de GeoJSON, mais simplement le formalisme Leaflet.
**On n'est pas obligé d'utiliser du GeoJSON dans Leaflet**, mais [on peut le faire si on veut](http://leafletjs.com/examples/geojson.html), en utilisant la méthode `.geoJson` de Leaflet.

```
var monGeoJSON = ... ;
var myLayer = L.geoJson(monGeoJSON);  // je crée une layer de type GeoJSON
myLayer.addTo(map); // j'ajoute ma layer à ma map
```

Du coup, en fait **tu as le choix**:
- soit tu utilises le formalisme GeoJSON, il faut donc un fichier au format GeoJSON, et utiliser les layers Leaflet de type geoJson
- soit tu te passes du GeoJSON, mais il faut s'astreindre à utiliser le formalisme Leaflet

Evidemment, il n'y a pas de meilleure réponse, chacun fait en fonction de ses préférences.

## Générer un fichier JSON

Pour écrire un fichier (JSON ou pas), il faut utiliser:

```
var fs = require('fs');

va maString = JSON.stringify(objetJSON); // je convertis mon objetJSON en texte pur pour pouvoir l'écrire dans un fichier

fs.writeFile('leNomQueJeVeuxDonner.extension', maString);
```

Attention, `fs` ne peut pas s'utiliser côté client (dans ton navigateur), il faut absolument lancer ton script côté serveur (en faisant `node monScript.js` dans ta console).

Voilà, j'espère avoir été clair, à défaut d'avoir été concis :)

**Comment by ThierryPolard** [comment]
Merci @iOiurson  pour ce retour clair
...mais je reviens avec une autre question !

J'ai l'impression que le format geojson est plus flexible à manipuler ensuite, j'ai donc tenté de créer un fichier.geosjon de cette façon : 

```

`var input2 = fs.createReadStream('./data/allData.json'); //lire le fichier json précédement crée

geojson.parse(input2, {Point: 'coords'}); // le parser en GeoJson

var geoData = JSON.stringify(input2); //  le convertir en texte

fs.writeFile('geoData.geojson', geoData); // l'écrire en geojson`
```

J'ai écrit ca dans un autre fichier, que j'ai appelé `convert.js`
Cela dit, il semble y avoit un pb car quand je lance le script côté serveur `node convert.js` sur ConEmu, je reçois ce msg d'erreur 

![image](https://cloud.githubusercontent.com/assets/16666814/12847730/8bae8392-cc15-11e5-8716-20ff7225652e.png)

Il semble y avoir un pb avec la fonction .forEach,  alors que celle-ci ne figure pas (explicitement en tout cas) dans le code, et  je ne comprends pas la première ligne du msg d'erreur qui pointe vers le module geoson dans node-module (`projetSirene2\node_modules\geojson\geojson.js:19:13`))

La aussi je suis allé regarder sur internet  : il y  pas mal de msg sur `XXX.forEach is not function` mais rien dont j'arrive a tirer partie pour avancer... Vu que l'erreur ne cible pas quelque chose que j'identifie, j'ai du mal a savoir ou chercher !

Merci !

**Comment by bleucitron** [comment]
Alors, plusieurs choses:

1) tu n'as pas besoin d'écrire

```
var input2 = fs.createReadStream('./data/allData.json');
```

La fonction `fs.createReadStream()` lit un fichier en stream (i.e, ligne par ligne). En gros, ca crée un object de type `Stream`, qui va émettre des évènements à chaque ligne lue, quand il y a une erreur de lecture, ou quand la lecture est terminée. C'est une fonction asynchrone. On utilise cette fonction surtout pour lire des fichiers que javascript ne sait pas lire par défaut, dans notre cas c'était les CSV.
Je pense que ton problème vient de là. Ton `input2` n'est pas une liste (comme l'est un GeoJSON), mais un objet de type Stream, et n'a donc pas la fonction `forEach()`. 

Il se trouve que le format a été créé pour être lu par Javascript. Ca veut dire JavaScript Object Notation. En gros c'est simplement un objet JS, mais écrit intégralement en string. C'est pour ça qu'en JSON tu vas avoir des "" partout. Le contenu d'un JSON est donc juste une ligne de string.

Quand tu veux lire un fichier JSON, tu as juste besoin de faire

```
var myJSON = require('./monFichierJSON.json');
```

Javascript sait lire ça tout seul, et il te crée automatiquement l'objet qui correspond à la string contenue dans le `.json`.

2) Tu n'as pas besoin d'écrire un fichier en dur à chaque manipulation. Tu as déjà un JSON qui contient da la donnée. Ce JSON on l'a écrit à partir d'un CSV. On l'a écrit en dur parce qu'on ne peut pas lire directement un CSV depuis un navigateur, alors qu'un JSON oui (je simplifie un peu là).
Une fois que tu as un JSON en dur, si tu veux l'enrichir, fais le directement dans ton script client, sans forcément réécrire un fichier à chaque fois.

**Comment by ThierryPolard** [comment]
Merci Romain @iOiurson  pour les conseils. Par contre, ça ne marche toujours pas.  :(

J'ai essayé de reprendre les étapes pas a pas, de simplifier le jeu de données (pour n'avoir qu'une seule valeur de paramètres) etc, mais je bute toujours au même endroit - et ce n'est pas bien loin.

Je créé en dur le fichier JSON  `fs.writeFile('../data/allData3.json',JSON.stringify(finalOutput));`
Il  a l'air de ressembler a ce que je veux)
![image](https://cloud.githubusercontent.com/assets/16666814/12854299/3b8f679a-cc39-11e5-97e2-983890292a4a.png)

je l’appelle avec ça :  `var myJSON = require('../data/allData3.json');`  et le console.log me laisse penser que le format n'est pas trop déconnant par rapport a ce qui est attendu (encore que j'aurai préféré qu'a la place d[objet] il m'affiche les date et valeur du paramètre]... 

![image](https://cloud.githubusercontent.com/assets/16666814/12854484/3855d3a6-cc3a-11e5-8568-7b688ea66ba3.png)

Ensuite, j'essaie d'en faire un geojson

`var MyGeoJSON = GeoJSON.parse(myJSON, {Point: 'coords', include:  ['Id'], exclude : ['oxygeneByDate']});`

Du coup, a priori je pense mouliner un format json connu, qui devrait avoir la fonction `forEach` ...

 ... mais je retombe sur le même msg d'erreur que tout à l'heure.

![image](https://cloud.githubusercontent.com/assets/16666814/12854454/1cb79576-cc3a-11e5-8aa4-432fb79c9ed8.png)

Si tu as une piste, je suis preneur ! ;)

Bon w-e,

**Comment by bleucitron** [comment]
Okay, je vois.
Le souci est que ton JSON est un objet d'objet:

```
{
    Thil: blablabla,
    Cantinolle: blablabla,
    ...
}
```

Les Objets en JS n'ont pas accès à `forEach`...

2 solutions:
1) Soit tu itères en faisant `Object.keys(myJson).forEach()`. `Object.keys()` permet de générer une liste contenant toutes les clés de ton objet (là ça serait Thil, Cantinolle...). Dans le `forEach` du coup tu peux accéder au contenu de chaque clé en faisant par exemple `myJson[key]`

```
Object.keys(myJson).forEach(function(key){
    console.log('ma clé: ', key, 'ma valeur: ', myJson[key]);
});
```

Le problème en faisant ça c'est que tu risques de perdre l'information du nom de ton point (qui est la clé, mais qui n'est pas présente dans la 'valeur'.

2) Soit tu t'arranges pour que ton JSON de base soit une liste d'objets et non un objet d'objets. Pour ça il faut que tu modifies ta façon de générer ton `finalOutput`. Il faudrait que je voies le code pour t'en dire plus. Un indice: fais un truc du genre:

```
var finalOutput = [];

// quand tu as créé un nouvel objet à ranger:
finalOutput.push({
   name: Thil,
   coords: [lat, lon],
   ...
});
```

J'espère que ça va te débloquer.
Sinon on en reparle mardi.

**Comment by bleucitron** [comment]
Et du coup je me rends compte que j'ai à moitié dit de la merde.

La solution 1) de mon commentaire précédent est valide quand tu veux itérer sur un objet, mais ça ne marchera pas dans ton cas. Pour utiliser le paquet `geojson.parse(input2, {Point: 'coords'});`, il faut que ton `input2` soit une liste.

Par exemple, sur la [doc du paquet `geojson`](https://www.npmjs.com/package/geojson), tu peux lire:

```
var data = [
  { name: 'Location A', category: 'Store', street: 'Market', lat: 39.984, lng: -75.343 },
  { name: 'Location B', category: 'House', street: 'Broad', lat: 39.284, lng: -75.833 },
  { name: 'Location C', category: 'Office', street: 'South', lat: 39.123, lng: -74.534 }
];

GeoJSON.parse(data, {Point: ['lat', 'lng']}); // attention ici, je ne suis pas sûr de l'ordre entre lng et lat
```

Il faut donc que tu t'arranges pour créer ton `finalOutput` en tant que liste.

**Comment by ThierryPolard** [comment]
Ok, merci. j'essaie de regarder ça demain (ou au pire d'ici mardi ;) )
